kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}--mssql-data-claim
  namespace: database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
   requests:
    storage: 1Gi