apiVersion: apps/v1
kind: Deployment
metadata:
  name: nonogram
  namespace: nonogram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nonogram
  template:
    metadata:
      labels:
        app: nonogram
    spec:
      containers:
        - name: nonogram
          image: nonogram:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 80
          env:
            - name : mssql_password
              valueFrom:
                secretKeyRef:
                  name: mssql
                  key: SA_PASSWORD