kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data-claim
  namespace: database
  #finalizers: null
spec:
  accessModes:
  - ReadWriteOnce
  resources:
   requests:
    storage: 1Gi