apiVersion: v1
kind: Service
metadata:
  name: nono-entrypoint
  namespace: nonogram
  labels:
    service: nonogram
spec:
  selector:
    app: nonogram
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 80
    nodePort: 30001
  type: LoadBalancer