apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}--nonogramapi
  namespace: {{ .Values.app.main }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.main }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.main }}
    spec:
      containers:
        - name: {{ .Values.app.main }}
          image: {{ .Values.image.name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.mainService.targetPort }}
          env:
            - name : {{ .Values.secret.envName }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: {{ .Values.secret.key }}