apiVersion: v1
kind: Service
metadata:
  name: mssql-deployment
  namespace: database
spec:
  selector:
    app: {{ .Values.app.database }}
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}--mssql-deployment
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.database }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.database }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD
        volumeMounts:
        - name: mssql-persistent-storage
          mountPath: /var/opt/mssql
      volumes:
      - name: mssql-persistent-storage
        persistentVolumeClaim:
          claimName: mssql-data-claim