apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.databaseService.name | default "mssql-deployment"}}
  namespace: {{ .Values.app.database}}
spec:
  selector:
    app: {{ .Values.app.database }}
  ports:
    - protocol: {{ .Values.databaseService.protocol }}
      port: {{ .Values.databaseService.port }}
      targetPort: {{ .Values.databaseService.targetPort }}
  type: {{ .Values.databaseService.type }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}--mssql-deployment
  namespace: {{ .Values.app.database}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.database }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.database }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: {{ .Values.secret.key }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: {{ .Values.secret.key }}
        volumeMounts:
        - name: mssql-persistent-storage
          mountPath: /var/opt/mssql
      volumes:
      - name: mssql-persistent-storage
        persistentVolumeClaim:
          claimName: mssql-data-claim